service: aws-serverless-skeleton

frameworkVersion: ">=2.1.0 <3.0.0"

package:
  patterns:
    - '!node_modules/**'
    - '!.idea/**'
    - '!.requirements/**'
    - '!env/**'
    - '!config/**'
    - '!README.md'
    - '!package.json'
    - '!package-lock.json'
    - '!requirements.txt'
    - '!requirements-dev.txt'
    - '!.tox/**'
    - '!.cache/**'
    - '!.serverless/**'
    - '!seed/**'
    - '!tests/**'
    - '!tox.ini'
    - '!.pytest_cache/**'
    - '!htmlcov/**'
    - 'config/resource/logging.yaml'

plugins:
  - serverless-python-requirements
  - serverless-dynamodb-local
  - serverless-offline

custom: ${file(config/${self:provider.stage}-env.yml):custom}

functions: ${file(config/${self:provider.stage}-env.yml):functions}

configValidationMode: warn

provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  stage: ${opt:stage, 'local'}
  environment: ${file(config/${self:provider.stage}-env.yml):environment}
  iam: ${file(config/resource/iam_policies.yml):iam}
  lambdaHashingVersion: 20201221

resources:
  - ${file(config/resource/cognito.yml)}
  - ${file(config/resource/dynamodb.yml)}
  - ${file(config/resource/rules.yml)}
  - ${file(config/resource/s3.yml)}
