iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DetachNetworkInterface
        - ec2:DeleteNetworkInterface
      Resource: "*"
    - Effect: "Allow"
      Action:
        - cloudwatch:PutMetricData
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource:
        - Fn::GetAtt: [ PostDynamoDbTable , Arn ]
        - Fn::GetAtt: [ UserDynamoDbTable , Arn ]
        - Fn::GetAtt: [ UploadDynamoDbTable , Arn ]
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        Fn::GetAtt: [ S3BucketUpload , Arn ]
#    - Effect: Allow
#      Action: es:ESHttpGet
#      Resource:
#        - 'Fn::Join':
#          - ':'
#          -
#            - 'arn:aws:es'
#            - Ref: 'AWS::Region'
#            - Ref: 'AWS::AccountId'
#            - 'Fn::Join':
#              - '/'
#              -
#                - 'domain'
#                - Ref: "ElasticSearchInstance"
#                - '*'